### ISSUE TITLE
[BUG] Text overflowing

### ISSUE THREAD

**Issue by ravinder-chadha** [gita/Bhagavad-Gita-App#109]
### 🙁 Actual behavior

1. The Verse of the day container on the home screen is not expandable.
<img src="https://user-images.githubusercontent.com/78102600/148795856-ee898c16-15da-464c-814a-56f4e16f5a70.jpg" width="120">

2. The About us page is not enclosed with the safe area, i.e., It flows into the status bar.
<img src="https://user-images.githubusercontent.com/78102600/148795848-1783d358-6ff1-45f5-9853-ef2601eff703.jpg" width="120">    <img src="https://user-images.githubusercontent.com/78102600/148795853-8957159a-a019-492b-9cf3-5ee315f8d878.jpg" width="120">

### 🙂 Expected behavior

1. Either the container must expand if we have a big verse, or the font size must reduce to adjust itself inside the container.
2. Enclose the about us page in the safe area. 

### 🔢 Steps to Reproduce the Problem

1. Install and visit the home page and scroll the about page.

**Comment by ravinder-chadha** [comment]
I would like to fix this myself.

**Comment by samanyougarg** [comment]
Thanks for identifying this bug Ravinder. That's very helpful since there are like 3500 active users and a lot of them might be facing these errors.

**Comment by pnaskardev** [comment]
Please assign me this problem

**Comment by Mehul-Kumar-27** [comment]
Hi, I would like to work on this issue.
