### ISSUE TITLE
"Last read" is not aligned properly

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#11]
There are some alignment issues with the "Last read".

This is how it looks like:
<img width="386" alt="Screenshot 2021-10-08 at 11 56 29 PM" src="https://user-images.githubusercontent.com/32533774/136608241-c4963119-a8cb-4cdd-8690-edc54a4f843c.png">

This is how it should look:
<img width="265" alt="Screenshot 2021-10-08 at 11 56 12 PM" src="https://user-images.githubusercontent.com/32533774/136608216-b7d078ef-9060-4f4f-892f-b6217098ceae.png">

Notice the gap above the button as well as

**Comment by jaydipgodhani** [comment]
Done
