### ISSUE TITLE
Fix Verse if the Day styling

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#12]
How it looks:
<img width="372" alt="Screenshot 2021-10-08 at 11 59 18 PM" src="https://user-images.githubusercontent.com/32533774/136608615-b5f19e69-73b7-481f-963c-34c2402fd37d.png">

How it should look:
<img width="475" alt="Screenshot 2021-10-08 at 11 59 04 PM" src="https://user-images.githubusercontent.com/32533774/136608540-0a48969a-443f-43e9-950f-8727e3487f21.png">

Issues:
1. Spacing up and down.
2. Color of the verse number like "11.21 |". Should be lighter orange.
3. READ MORE should be all capital.

**Comment by jaydipgodhani** [comment]
Done.
