### ISSUE TITLE
Sorting feature doesn't work

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#13]
Clicking this button sort sort the chapters by asc or desc order.

<img width="385" alt="Screenshot 2021-10-09 at 12 01 55 AM" src="https://user-images.githubusercontent.com/32533774/136608866-f02f78df-8f31-4d3c-8701-245cbaa1b4e7.png">

**Comment by jaydipgodhani** [comment]
Done
