### ISSUE TITLE
Three dots buttons are broken on notes and bookmarks page

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#16]
Three dots buttons are broken on bookmarks page.

<img width="389" alt="Screenshot 2021-10-09 at 12 06 02 AM" src="https://user-images.githubusercontent.com/32533774/136609308-4a706082-faf9-4de9-a57e-40aae3f36dc1.png">

<img width="386" alt="Screenshot 2021-10-09 at 12 07 00 AM" src="https://user-images.githubusercontent.com/32533774/136609417-3b785659-8aaf-4732-8d62-5c262aa432a3.png">

**Comment by jaydipgodhani** [comment]
Done.
