### ISSUE TITLE
Increase the click area for notes

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#17]
Can we increase the click area for the notes so user can click anywhere on the screen to go to the text area?

<img width="389" alt="Screenshot 2021-10-09 at 12 07 35 AM" src="https://user-images.githubusercontent.com/32533774/136609484-fd968833-7ec6-4c58-9af6-b50e99621b7b.png">

**Comment by jaydipgodhani** [comment]
Done
