### ISSUE TITLE
Double clicking the bookmark or notes tabs doesn't allowing further clicks

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#18]
If you double click on "Book Mark" or "Notes" tabs on the Saved screen, it will not let you load the Notes screen.

![bookmark](https://user-images.githubusercontent.com/32533774/136609787-96e2ecf5-4197-468d-b046-5766fc578b46.gif)

**Comment by jaydipgodhani** [comment]
Done.
