### ISSUE TITLE
How does a user delete a note on the verse page?

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#22]
Currently, there is no option to delete a note from the verse page.

![Screenshot_1633718920](https://user-images.githubusercontent.com/32533774/136610668-3460219c-523d-4263-b912-044a31ae8208.png)

**Comment by jaydipgodhani** [comment]
There is no option to delete in Figma also. Please give some information.

**Comment by jaydipgodhani** [comment]
Well we put Delete button

**Comment by jaydipgodhani** [comment]
Done.
