### ISSUE TITLE
Language selection doesn't load the default language

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#23]
![Screenshot_1633718995](https://user-images.githubusercontent.com/32533774/136610802-d3fcd395-cb41-4aae-a1f1-4c92d3b4cad3.png)

**Comment by jaydipgodhani** [comment]
I am not getting this one, Default languages means, You mean show tick for the already selected one.

**Comment by jaydipgodhani** [comment]
Done.
