### ISSUE TITLE
"Verse of the day" notification time selection doesn't look good

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#24]
<img width="393" alt="Screenshot 2021-10-09 at 12 20 59 AM" src="https://user-images.githubusercontent.com/32533774/136610909-46eb09a0-232c-42c2-9465-37b15848a793.png">

Can we make it look like the designs?
<img width="289" alt="Screenshot 2021-10-09 at 12 21 42 AM" src="https://user-images.githubusercontent.com/32533774/136610973-57a8b8bf-66e1-46b6-9c95-d698f65aa823.png">

**Comment by jaydipgodhani** [comment]
It;s still remaining, Need to discuss how notification is work in our system, Notification is managed by backend?

**Comment by jaydipgodhani** [comment]
Done
