### ISSUE TITLE
Lots of buttons don't have any click animation effect

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#26]
1. 
![Screenshot_1633719286](https://user-images.githubusercontent.com/32533774/136611337-22c28d36-ec3d-4bd5-985f-cafed01997a7.png)

2.
<img width="312" alt="Screenshot 2021-10-09 at 12 25 29 AM" src="https://user-images.githubusercontent.com/32533774/136611409-b2a36a7b-e8f0-48e6-8580-2a3e9b3c8186.png">

 3.
<img width="389" alt="Screenshot 2021-10-09 at 12 26 19 AM" src="https://user-images.githubusercontent.com/32533774/136611564-c7f08d66-2994-44cf-bf72-dc5fe7354b2a.png">

**Comment by jaydipgodhani** [comment]
Done.
