### ISSUE TITLE
Call the API on homescreen only once

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#33]
Instead of calling the APIs every time user opens this screens, can we only load it once at the time of app launch?

![Screenshot_20211021-225441](https://user-images.githubusercontent.com/32533774/138327108-12b3395d-d5b9-4848-9dfe-9e0bb5c4c644.jpg)

**Comment by jaydipgodhani** [comment]
if user change the tab and return to back to home screen that time flutter rebuild the widget so automatically api calls.

**Comment by jaydipgodhani** [comment]
done.

**Comment by samanyougarg** [comment]
This seems to be blank now.
<img width="383" alt="Screenshot 2021-10-22 at 9 05 09 PM" src="https://user-images.githubusercontent.com/32533774/138482987-d008b5c6-2528-4031-81c6-27bd1f3f6e8e.png">

**Comment by jaydipgodhani** [comment]
Done
