### ISSUE TITLE
Reduce spacing between the text elements on verse details page

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#35]
When the user selects the checkboxes for different things like translations, commentary etc, it adds a lot of space in between. Please remove the extra space.

![Screenshot_20211021-225718](https://user-images.githubusercontent.com/32533774/138327463-5454fe01-db3b-42f6-95d2-38d64a15c73e.jpg)

**Comment by jaydipgodhani** [comment]
Done.
