### ISSUE TITLE
Can we make navigation buttons like this

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#38]
Can we make navigation buttons like this?

So, the buttons hide when scrolling down and stick to the bottom when we reach the end.
If we scroll up, the buttons are shown again.

**Comment by samanyougarg** [comment]
https://user-images.githubusercontent.com/32533774/138329147-7bc00344-5177-4840-aad0-1819f00176f5.mp4

**Comment by jaydipgodhani** [comment]
Done.
