### ISSUE TITLE
Exceptions on app startup

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#39]
Please fix all the exceptions.

App is not working on a virtual device I tried.
<img width="383" alt="Screenshot 2021-10-21 at 11 10 46 PM" src="https://user-images.githubusercontent.com/32533774/138329371-1873a352-3bb5-498a-b489-f91811c9fbde.png">

**Comment by samanyougarg** [comment]
<img width="1276" alt="Screenshot 2021-10-21 at 11 05 47 PM" src="https://user-images.githubusercontent.com/32533774/138328659-a5463c2a-5b7e-4a0e-87d0-005723753f51.png">

**Comment by samanyougarg** [comment]
<img width="1466" alt="Screenshot 2021-10-21 at 11 06 10 PM" src="https://user-images.githubusercontent.com/32533774/138328708-13d2325e-ea33-46d1-981a-3ec301d3a5de.png">

**Comment by samanyougarg** [comment]
<img width="1665" alt="Screenshot 2021-10-21 at 11 06 59 PM" src="https://user-images.githubusercontent.com/32533774/138328825-ff41e8ec-ae3e-4bae-8bba-59548030798c.png">

**Comment by samanyougarg** [comment]
<img width="1308" alt="Screenshot 2021-10-21 at 11 07 14 PM" src="https://user-images.githubusercontent.com/32533774/138328862-216cc126-9f53-41ce-b0b5-f51cde4468e1.png">

**Comment by jaydipgodhani** [comment]
Done.
