### ISSUE TITLE
Dropdowns not opening at correct places

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#4]
So, the dropdowns always open at the top for Saved/Notes screens.

For example, here I clicked the third `...` button.
<img width="381" alt="Screenshot 2021-09-29 at 7 59 29 AM" src="https://user-images.githubusercontent.com/32533774/135193039-b37dd86f-f6be-4e80-8566-96591e440637.png">

but the dropdown was opened at the top:
<img width="408" alt="Screenshot 2021-09-29 at 7 59 53 AM" src="https://user-images.githubusercontent.com/32533774/135193002-740416ab-c202-4743-b5d6-195c597e039c.png">

**Comment by jaydipgodhani** [comment]
Done.
