### ISSUE TITLE
Make button ripple round

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#43]
If you see the next/prev buttons, the click effect is square which looks bad. Please make it round.
![Screenshot_20211021-231925](https://user-images.githubusercontent.com/32533774/138330624-bd8264e7-877e-419f-a0da-25528648ab21.jpg)

**Comment by jaydipgodhani** [comment]
Done

**Comment by samanyougarg** [comment]
<img width="388" alt="Screenshot 2021-10-22 at 9 03 30 PM" src="https://user-images.githubusercontent.com/32533774/138482694-0e772df8-af05-4507-b231-8f9e6f5af465.png">

**Comment by samanyougarg** [comment]
The effect seems to be on the shadow instead of the button.

**Comment by jaydipgodhani** [comment]
Done
