### ISSUE TITLE
Select default translation and commentary based on language

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#47]
If the user selects English language, can we show these by default:
1. Transliteration switch should be on
2. Translation should be "English translation by Swami Adidevananda"
3. Commentary should be "English commentary by Swami Sivananda"

If the user selects Hindi language, can we show these by default:
1. Transliteration switch should be off
2. Translation should be "Hindi translation by Swami Tejomayananda"
3. Commentary should be "Hindi commentary by Swami Chinmayandanda"

**Comment by jaydipgodhani** [comment]
Done.
