### ISSUE TITLE
Onboarding screens are very laggy

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#50]
https://user-images.githubusercontent.com/32533774/138332865-126d5e1c-4c3b-4e25-8caa-43a062d4ea03.mp4

**Comment by jaydipgodhani** [comment]
I think you are running debug build that's why it's shows laggy

**Comment by samanyougarg** [comment]
Yes, that's right. What would be a way to test the normal build?

**Comment by jaydipgodhani** [comment]
you need to run below command 
1-> flutter clean
2-> flutter build app --release
