### ISSUE TITLE
Clicking the Next button on chapter 18 verse 78 gives null error

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#55]
Chapter 18 verse 78 is the last verse. So, the next button shouldn't be displayed.

<img width="388" alt="Screenshot 2021-10-22 at 9 10 22 PM" src="https://user-images.githubusercontent.com/32533774/138483732-636cf096-52db-45d6-8666-38eb2c577941.png">

**Comment by jaydipgodhani** [comment]
Done.
