### ISSUE TITLE
Fix chapter page scroll

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#6]
Currently, on the chapter page, the background is fixed whereas all the text is scrollable. This makes the text less readable.

Can we please make the background scroll along with the page?

<img width="391" alt="Screenshot 2021-10-08 at 11 43 20 PM" src="https://user-images.githubusercontent.com/32533774/136603521-c6e30ac2-5a13-4f7f-820a-c247f9e5dca9.png">

**Comment by jaydipgodhani** [comment]
Done.
