### ISSUE TITLE
Padding for commentary doesn't look good

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#61]
When the translation is disabled, the padding for commentary doesn't look good. Please reduce it.

![Screenshot_20211030-103416](https://user-images.githubusercontent.com/32533774/139521246-9b9a7399-0a04-48fb-ac3d-7fb262545dac.jpg)

**Comment by samanyougarg** [comment]
![Screenshot_20211030-103332](https://user-images.githubusercontent.com/32533774/139521315-30a4dd08-ea6b-4f48-ab21-5c4e6f772fd1.jpg)

**Comment by jaydipgodhani** [comment]
Done.
