### ISSUE TITLE
Bookmark is not saving correctly

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#63]
If I click the bookmark button:
1. If I use the next/previous buttons to change verse page, the bookmark is lost.
2. The bookmarked verse doesn't appear on the "Book Mark" page
https://user-images.githubusercontent.com/32533774/139521362-f0257a04-83c4-466a-aaaf-e4b4f187e9e5.mp4

**Comment by jaydipgodhani** [comment]
Done.
