### ISSUE TITLE
Chapter title and summary doesn't change on language change

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#66]
Here I selected hindi as language, but the chapter title and summary still shows in english.
![Screenshot_20211030-105843](https://user-images.githubusercontent.com/32533774/139521691-f615adc8-19e5-4f9a-9ba5-bdadef0a7971.jpg)

**Comment by jaydipgodhani** [comment]
Chapter summery coming from the api and there is no parameter for language.
