### ISSUE TITLE
"Verse of the day" and "Last Read" doesn't change language on language selection

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#70]
1. Let's say I first use the app in English language.
2. Now, I change the language to Hindi.
3. "Verse of the day" and "Last Read" are still in English and do not change to Hindi.

Similarly, 
1. Let's say I first use the app in Hindi language.
2. Now, I change the language to English.
3. "Verse of the day" and "Last Read" are still in Hindi and do not change to English.

<img width="506" alt="Screenshot 2021-10-30 at 11 11 35 AM" src="https://user-images.githubusercontent.com/32533774/139521819-f48f9c40-f62a-4495-9e58-934d9f2d9a0e.png">

https://user-images.githubusercontent.com/32533774/139521807-3810b894-8e71-4d8d-b4ea-b890552b8aa5.mp4

**Comment by jaydipgodhani** [comment]
Last read was managed by the locally so not able to change language when language changed.

**Comment by jaydipgodhani** [comment]
Done.
