### ISSUE TITLE
Fix errors in AndroidManifest.xml and fix launcher icon

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#79]
Fix errors in manifest
<img width="1031" alt="Screenshot 2021-11-01 at 11 22 14 PM" src="https://user-images.githubusercontent.com/32533774/139717209-253ea140-6d47-41f3-90b6-48c404b76b46.png">

**Comment by jaydipgodhani** [comment]
this error is ignorable from fluter side. It's not cause any issue.
