### ISSUE TITLE
App not working when setting targetSdkVersion to 31 in build.gradle 

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#80]
App not working when setting targetSdkVersion to 31 in build.gradle

**Comment by VICKY2501** [comment]
targetSdkVersion is higher than compileSdkVersion is one of the reason of your app does'nt work properly change targetSdkversion to 30.0.2

**Comment by jaydipgodhani** [comment]
set compileSdkversion and targetSdkVersion
