### ISSUE TITLE
The Quotes are Random 

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/Bhagavad-Gita-App#90]
The quotes generated on Quotes section doesn't follow the order of next and previous as shown in UI buttons,
if from a quote we go Next, there is a new quote and on going back the previous is not recovered, we get a new quote instead

https://user-images.githubusercontent.com/64721638/142723979-22c1ae50-3a74-4610-8455-9e09b97a60c5.mp4

**Comment by champ96k** [comment]
@Gupta-Anubhav12 can you please assign me this issue?  I can fix that.

**Comment by Gupta-Anubhav12** [comment]
Sure
Thanks for taking this up

**Comment by samanyougarg** [comment]
@champ96k any updates on this?

**Comment by ravinder-chadha** [comment]
I will like to fix this, kindly assign me this.
