### ISSUE TITLE
[BUG] Verse of the day is not appearing on home screen

### ISSUE THREAD

**Issue by samanyougarg** [gita/Bhagavad-Gita-App#96]
### 🙁 Actual behavior

Verse of the day is not appearing for some reason.

### 🙂 Expected behavior

Verse of the day should be queried from the GraphQL API and if it exists, the given verse should be shown on the "Verse of the day" card on home screen.

Like this: https://play-lh.googleusercontent.com/VOOZ99xi2I6XiGJVMWmtuPtU3EYk_P3BVW_PggLoepkXUZUZ5E83Ww098bIHjCtAHM4=w1440-h620-rw

### 🔢 Steps to Reproduce the Problem

1. Open the app.
2. Check the home screen.

<img width="387" alt="Screenshot 2021-12-29 at 9 14 27 PM" src="https://user-images.githubusercontent.com/32533774/147679320-60bc32a4-449a-42df-b48d-b9786f8e6000.png">

**Comment by Gupta-Anubhav12** [comment]
![image](https://user-images.githubusercontent.com/64721638/147682071-e407b394-70f4-49e7-8fc3-aab0472d0e60.png)
The backend gives verse number for verse of the day, 
it would be better to have one-to-one relation with this verse_number and verse table to do the job in single query
whereas right now a quick fix would be to fetch the verse from a separate query at front end 
will fix backend soon, and try hands on flutter :smile:

**Comment by Gupta-Anubhav12** [comment]
Issue solved
